# =============================================================================
# DEV ENVIRONMENT - Terraform Variables
# =============================================================================
# Auto-generated by import_from_grafana.py on 2026-03-10T04:20:49.555688
#
# Usage:
#   make plan  ENV=dev
#   make apply ENV=dev
# =============================================================================

# The URL of your Grafana instance
grafana_url = "http://localhost:3000"

# Direct Grafana auth — used when use_vault is false.
# Format: "admin:password" or a service-account/API token (glsa_...).
grafana_auth = "admin:admin"

# Environment name — must match a directory under envs/
environment = "dev"

# ─── Vault Configuration (OPTIONAL) ────────────────────────────────────────
# Set use_vault = true to enable Vault-based secrets management.
# When false (default), grafana_auth above is used directly.
use_vault     = true
vault_address = "http://localhost:8200"
vault_mount   = "grafana"

# Vault Enterprise namespace (leave commented for OSS Vault or root namespace)
# vault_namespace = "admin/team-grafana"

# vault_token — set via VAULT_TOKEN env variable for security:
#   export VAULT_TOKEN="your-vault-token"

# ─── Vault Secret Paths ────────────────────────────────────────────────────
# Provider-level auth paths (Grafana + Keycloak login).
# All other secrets use VAULT_SECRET_REQUIRED:<path>:<key> directly in YAML configs.
#
# vault_path_grafana_auth      = "{env}/grafana/auth"
# vault_path_keycloak          = "{env}/keycloak/client"

# Keycloak Configuration (optional — only if you enable SSO via Keycloak)
# keycloak_url = "https://keycloak.example.com"
