#!/usr/bin/env python3
"""
Import from Grafana — Generate YAML configs from an existing instance.

Connects to a running Grafana instance and generates YAML configuration
files that can be used with this Terraform framework.

Usage:
    python scripts/import_from_grafana.py prod \
        --grafana-url=https://grafana.example.com \
        --auth=admin:admin
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

from importers.common import Colors, GrafanaClient, ImportContext, yaml_dump
from importers import (
    import_organizations,
    import_datasources,
    import_folders,
    import_teams,
    import_service_accounts,
    import_alerting,
    import_dashboards,
    import_sso,
)


# =============================================================================
# Generate tfvars
# =============================================================================
def generate_tfvars(ctx: ImportContext) -> None:
    """Generate terraform.tfvars file if it doesn't exist."""
    tfvars_file = ctx.config_dir / "terraform.tfvars"

    if tfvars_file.exists():
        print(f"  {Colors.DIM}  envs/{ctx.env_name}/terraform.tfvars already exists (skipped){Colors.NC}")
        return

    auth_value = ctx.client.auth

    content = f"""# =============================================================================
# {ctx.env_name.upper()} ENVIRONMENT - Terraform Variables
# =============================================================================
# Auto-generated by import_from_grafana.py on {datetime.now().isoformat()}
#
# Usage:
#   make plan  ENV={ctx.env_name}
#   make apply ENV={ctx.env_name}
# =============================================================================

# The URL of your Grafana instance
grafana_url = "{ctx.grafana_url}"

# Direct Grafana auth — used when use_vault is false.
# Format: "admin:password" or a service-account/API token (glsa_...).
grafana_auth = "{auth_value}"

# Environment name — must match a directory under envs/
environment = "{ctx.env_name}"

# ─── Vault Configuration (OPTIONAL) ────────────────────────────────────────
# Set use_vault = true to enable Vault-based secrets management.
# When false (default), grafana_auth above is used directly.
use_vault     = false
vault_address = "http://localhost:8200"
vault_mount   = "{ctx.vault_mount}"

# Vault Enterprise namespace (leave commented for OSS Vault or root namespace)
# vault_namespace = "{f'{ctx.vault_namespace}' if ctx.vault_namespace else 'admin/team-grafana'}"

# vault_token — set via VAULT_TOKEN env variable for security:
#   export VAULT_TOKEN="your-vault-token"

# ─── Vault Secret Paths ────────────────────────────────────────────────────
# Provider-level auth paths (Grafana + Keycloak login).
# All other secrets use VAULT_SECRET_REQUIRED:<path>:<key> directly in YAML configs.
#
# vault_path_grafana_auth      = "{{env}}/grafana/auth"
# vault_path_keycloak          = "{{env}}/keycloak/client"

# Keycloak Configuration (optional — only if you enable SSO via Keycloak)
# keycloak_url = "https://keycloak.example.com"
"""

    with open(tfvars_file, "w") as f:
        f.write(content)

    print(f"  {Colors.GREEN}✓{Colors.NC} Generated envs/{ctx.env_name}/terraform.tfvars")


# =============================================================================
# Summary
# =============================================================================
def print_summary(ctx: ImportContext) -> None:
    """Print import summary."""
    print("")
    print(f"{Colors.GREEN}╔═══════════════════════════════════════════════════════════════╗{Colors.NC}")
    print(f"{Colors.GREEN}║  Import complete!{Colors.NC}")
    print(f"{Colors.GREEN}╚═══════════════════════════════════════════════════════════════╝{Colors.NC}")
    print("")
    print(f"  Source:      {ctx.grafana_url}")
    print(f"  Target env:  {ctx.env_name}")
    print(f"  Orgs:        {len(ctx.org_ids)} ({' '.join(str(i) for i in ctx.org_ids)})")
    print(f"  Imported:    {ctx.imported_count} resource type(s)")
    print("")
    print("  Generated files:")
    print(f"    envs/{ctx.env_name}/")

    for f in sorted(ctx.config_dir.iterdir()):
        if f.is_file():
            print(f"      {f.name}")

    for resource in ("datasources", "folders", "teams", "service_accounts"):
        resource_dir = ctx.config_dir / resource
        if resource_dir.exists():
            print(f"      {resource}/")
            for org_dir in sorted(resource_dir.iterdir()):
                if org_dir.is_dir():
                    count = sum(1 for _ in org_dir.iterdir())
                    print(f"        {org_dir.name}/  ({count} file(s))")

    alerting_dir = ctx.config_dir / "alerting"
    if alerting_dir.exists():
        print(f"    envs/{ctx.env_name}/alerting/ (one subdir per org)")
        for org_dir in sorted(alerting_dir.iterdir()):
            if org_dir.is_dir():
                count = sum(1 for _ in org_dir.iterdir())
                print(f"        {org_dir.name}/  ({count} file(s))")

    if ctx.import_dashboards:
        dash_dir = ctx.output_dir / "envs" / ctx.env_name / "dashboards"
        if dash_dir.exists():
            dash_count = len(list(dash_dir.rglob("*.json")))
            print(f"    envs/{ctx.env_name}/dashboards/ ({dash_count} dashboards)")
            for org_id in ctx.org_ids:
                org_name = ctx.org_map[org_id]
                org_dash_dir = dash_dir / org_name
                if org_dash_dir.exists():
                    org_dash_count = len(list(org_dash_dir.rglob("*.json")))
                    print(f"      {org_name}: {org_dash_count} dashboards")

    if ctx.tf_imports:
        print(f"\n  Terraform state imports: {len(ctx.tf_imports)} resource(s)")

    print("")
    print(f"  {Colors.YELLOW}⚠  Review and adjust the generated YAML files before applying!{Colors.NC}")
    print("  Some values (SSO, secrets, Keycloak) need manual configuration.")
    print("")
    print("  Next steps:")
    if ctx.skip_tf_import:
        print(f"    1. Review envs/{ctx.env_name}/*.yaml")
        print(f"    2. Review envs/{ctx.env_name}/terraform.tfvars")
    else:
        print(f"    1. Review envs/{ctx.env_name}/*.yaml")
        print(f"    2. Review envs/{ctx.env_name}/terraform.tfvars")
    print(f"    3. Set up Vault secrets: make vault-setup ENV={ctx.env_name}")
    print(f"    4. Run: make init ENV={ctx.env_name} && make plan ENV={ctx.env_name}")
    print("")


# =============================================================================
# Terraform State Import
# =============================================================================
def _resolve_backend(ctx: ImportContext) -> tuple[str, Path | None]:
    """Resolve backend type and tfbackend file path.

    Returns (backend_type, tfbackend_path_or_None).

    Priority:
    1. Explicit --backend + --backend-config from CLI
    2. Auto-detect from existing <env>.<type>.tfbackend files
    3. Default: local backend
    """
    env_dir = ctx.output_dir / "envs" / ctx.env_name
    backend_type = ctx.backend  # default "local"

    # --- User supplied --backend-config: write a tfbackend file ---------------
    if ctx.backend_config:
        # Map common aliases to Terraform backend names
        type_map = {"s3": "s3", "azurerm": "azurerm", "gcs": "gcs",
                    "gitlab": "http", "http": "http", "local": "local"}
        backend_type = type_map.get(backend_type, backend_type)

        filename = f"{ctx.env_name}.{backend_type}.tfbackend"
        tfbackend_path = env_dir / filename
        lines = [
            f"# Auto-generated by import_from_grafana.py — {backend_type} backend",
            f"# Usage:  make init ENV={ctx.env_name}",
            "",
        ]
        for kv in ctx.backend_config:
            if "=" in kv:
                k, v = kv.split("=", 1)
                lines.append(f'{k.strip()} = "{v.strip()}"')
            else:
                lines.append(kv)
        tfbackend_path.write_text("\n".join(lines) + "\n")
        print(f"  {Colors.GREEN}✓{Colors.NC} Generated envs/{ctx.env_name}/{filename}")
        return backend_type, tfbackend_path

    # --- Auto-detect from existing tfbackend files ----------------------------
    backend_files = sorted(env_dir.glob(f"{ctx.env_name}.*.tfbackend"))
    if not backend_files:
        backend_files = sorted(env_dir.glob("backend.tfbackend"))
    if backend_files:
        bf = backend_files[0]
        parts = bf.stem.split(".", 1)
        detected = parts[1] if len(parts) > 1 else "local"
        return detected, bf

    # --- Fallback: generate a local.tfbackend --------------------------------
    tfbackend_path = env_dir / f"{ctx.env_name}.local.tfbackend"
    tfbackend_path.write_text(
        f"# =============================================================================\n"
        f"# BACKEND CONFIGURATION \u2014 {ctx.env_name}\n"
        f"# =============================================================================\n"
        f"# Usage:  make init ENV={ctx.env_name}\n"
        f"# =============================================================================\n"
        f"\n"
        f"# --- Local Backend ---\n"
        f"# See: https://developer.hashicorp.com/terraform/language/backend/local\n"
        f"\n"
        f"# State file is stored per-environment inside the envs/ directory.\n"
        f'path = "../envs/{ctx.env_name}/terraform.tfstate"\n'
        f"\n"
        f"# Workspace directory (optional, uncomment to customise)\n"
        f'# workspace_dir = "../envs/{ctx.env_name}/workspaces"\n'
    )
    print(f"  {Colors.GREEN}✓{Colors.NC} Generated envs/{ctx.env_name}/{tfbackend_path.name}")
    return "local", tfbackend_path


def run_terraform_imports(ctx: ImportContext) -> None:
    """Run terraform import for all tracked resources."""
    if not ctx.tf_imports:
        print(f"\n  {Colors.DIM}No resources to import into Terraform state.{Colors.NC}")
        return

    print(f"\n{Colors.BLUE}[TF]{Colors.NC} Importing {len(ctx.tf_imports)} resource(s) into Terraform state...")

    tf_dir = ctx.output_dir / "terraform"
    var_file = f"../envs/{ctx.env_name}/terraform.tfvars"

    if not tf_dir.is_dir():
        print(f"  {Colors.RED}✗ Terraform directory not found: {tf_dir}{Colors.NC}")
        return

    # Step 1: resolve backend type + config file
    backend_type, tfbackend_path = _resolve_backend(ctx)
    backend_tf = tf_dir / "backend.tf"
    backend_tf.write_text(f'terraform {{\n  backend "{backend_type}" {{}}\n}}\n')

    # Step 2: terraform init
    print(f"  {Colors.DIM}Running terraform init (backend={backend_type})...{Colors.NC}")
    init_cmd = ["terraform", "init", "-input=false"]

    if tfbackend_path and backend_type != "local":
        init_cmd += [f"-backend-config=../envs/{ctx.env_name}/{tfbackend_path.name}", "-reconfigure"]
    elif tfbackend_path and backend_type == "local":
        # Pass local config too (supports custom path if uncommented)
        init_cmd += [f"-backend-config=../envs/{ctx.env_name}/{tfbackend_path.name}", "-reconfigure"]
    else:
        init_cmd += ["-reconfigure"]

    result = subprocess.run(
        init_cmd,
        cwd=str(tf_dir),
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print(f"  {Colors.RED}✗ terraform init failed:{Colors.NC}")
        for line in result.stderr.strip().splitlines()[-5:]:
            print(f"    {line}")
        return

    print(f"  {Colors.GREEN}✓{Colors.NC} terraform init OK")

    # Step 2: Import each resource
    imported = 0
    skipped = 0
    failed = 0

    for address, import_id in ctx.tf_imports:
        result = subprocess.run(
            ["terraform", "import", f"-var-file={var_file}", "-input=false", address, import_id],
            cwd=str(tf_dir),
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            imported += 1
            print(f"  {Colors.GREEN}✓{Colors.NC} {address}")
        elif "Resource already managed" in result.stderr or "already exists" in result.stderr.lower():
            skipped += 1
            print(f"  {Colors.DIM}  ● {address} (already in state){Colors.NC}")
        else:
            failed += 1
            err_lines = [l for l in result.stderr.strip().splitlines() if l.strip() and "Error:" in l]
            err_msg = err_lines[0].strip() if err_lines else result.stderr.strip().splitlines()[-1] if result.stderr.strip() else "unknown error"
            print(f"  {Colors.YELLOW}⚠{Colors.NC} {address} — {err_msg}")

    parts = []
    if imported:
        parts.append(f"{Colors.GREEN}{imported} imported{Colors.NC}")
    if skipped:
        parts.append(f"{Colors.DIM}{skipped} already in state{Colors.NC}")
    if failed:
        parts.append(f"{Colors.YELLOW}{failed} failed{Colors.NC}")
    print(f"\n  Terraform import: {', '.join(parts)}")

    # ── Post-import reconciliation ──────────────────────────────────────────
    # After `terraform import`, certain attributes are missing from state
    # because the provider can't read them back (e.g. empty preference blocks,
    # dashboard message/overwrite API params, notification-policy defaults).
    # A targeted apply on safe modules fixes this without touching contact-points
    # that contain [REDACTED] / VAULT_SECRET_REQUIRED placeholder secrets.
    # ────────────────────────────────────────────────────────────────────────
    safe_targets = [
        "-target=module.organizations",
        "-target=module.teams",
        "-target=module.dashboards",
        "-target=module.datasources",
        "-target=module.sso",
    ]
    # Include individual notification-policy resources (safe, no sensitive values)
    for address, _ in ctx.tf_imports:
        if "grafana_notification_policy.policy" in address:
            safe_targets.append(f"-target={address}")

    print(f"\n  {Colors.DIM}Reconciling state (targeted apply)...{Colors.NC}")
    apply_cmd = [
        "terraform", "apply",
        f"-var-file={var_file}",
        "-auto-approve",
        "-input=false",
        "-lock=false",
        "-refresh=false",
    ] + safe_targets

    result = subprocess.run(
        apply_cmd,
        cwd=str(tf_dir),
        capture_output=True,
        text=True,
    )
    if result.returncode == 0:
        # Count actual changes from output
        import re as _re
        m = _re.search(r"(\d+) added.*?(\d+) changed.*?(\d+) destroyed", result.stdout)
        if m:
            added, changed, destroyed = m.groups()
            total_reconciled = int(added) + int(changed) + int(destroyed)
            if total_reconciled:
                print(f"  {Colors.GREEN}✓{Colors.NC} Reconciled {total_reconciled} resource(s)")
            else:
                print(f"  {Colors.GREEN}✓{Colors.NC} State already in sync")
        else:
            print(f"  {Colors.GREEN}✓{Colors.NC} Reconciliation complete")
    else:
        print(f"  {Colors.YELLOW}⚠{Colors.NC} Reconciliation had issues (non-fatal):")
        for line in result.stderr.strip().splitlines()[-3:]:
            print(f"    {line}")


# =============================================================================
# Main Entry Point
# =============================================================================
def main() -> int:
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Import Grafana configuration into YAML files for Terraform.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    # Local backend (default):
    python scripts/import_from_grafana.py prod --grafana-url=http://localhost:3000 --auth=admin:admin

    # S3 backend:
    python scripts/import_from_grafana.py prod --grafana-url=https://grafana.example.com --auth=glsa_xxx \\
        --backend=s3 --backend-config=bucket=my-tf-state --backend-config=key=prod/grafana.tfstate \\
        --backend-config=region=us-east-1

    # Azure backend:
    python scripts/import_from_grafana.py staging --grafana-url=https://grafana.example.com --auth=glsa_xxx \\
        --backend=azurerm --backend-config=resource_group_name=my-rg \\
        --backend-config=storage_account_name=mytfstate --backend-config=container_name=tfstate \\
        --backend-config=key=staging/grafana.tfstate
        """,
    )
    parser.add_argument("env_name", help="Target environment name")
    parser.add_argument("--grafana-url", required=True, help="Grafana instance URL")
    parser.add_argument("--auth", required=True, help="API token or user:password")
    parser.add_argument("--no-dashboards", action="store_true", help="Skip dashboard import")
    parser.add_argument("--no-tf-import", action="store_true", help="Skip terraform state import (only generate YAML)")
    parser.add_argument("--backend", default="local",
                        help="Terraform backend type: local, s3, azurerm, gcs, http/gitlab (default: local)")
    parser.add_argument("--backend-config", action="append", default=[], metavar="KEY=VALUE",
                        help="Backend config key=value (repeatable). E.g. --backend-config=bucket=my-bucket")
    parser.add_argument("--vault-mount", default="grafana", help="Vault KV mount name — used in generated path hints (default: grafana)")
    parser.add_argument("--vault-namespace", default="", help="Vault Enterprise namespace — prepended to path hints (default: none)")
    parser.add_argument("--output-dir", help="Output directory (default: project root)")

    args = parser.parse_args()

    # Determine paths
    script_dir = Path(__file__).resolve().parent
    project_root = script_dir.parent
    output_dir = Path(args.output_dir) if args.output_dir else project_root
    config_dir = output_dir / "envs" / args.env_name

    # Create directories
    config_dir.mkdir(parents=True, exist_ok=True)
    (config_dir / "alerting").mkdir(parents=True, exist_ok=True)

    # Create client and context
    grafana_url = args.grafana_url.rstrip("/")
    client = GrafanaClient(url=grafana_url, auth=args.auth)

    ctx = ImportContext(
        env_name=args.env_name,
        grafana_url=grafana_url,
        client=client,
        output_dir=output_dir,
        config_dir=config_dir,
        import_dashboards=not args.no_dashboards,
        skip_tf_import=args.no_tf_import,
        vault_mount=args.vault_mount,
        vault_namespace=args.vault_namespace,
        backend=args.backend,
        backend_config=args.backend_config,
    )

    # Print header
    print(f"{Colors.BOLD}{Colors.CYAN}")
    print("╔═══════════════════════════════════════════════════════════════╗")
    print(f"║          Importing from Grafana → {args.env_name}")
    print("╚═══════════════════════════════════════════════════════════════╝")
    print(f"{Colors.NC}")

    # Test connection
    health = client.health()
    if health and health.get("database") == "ok":
        version = health.get("version", "unknown")
        print(f"  {Colors.GREEN}✓{Colors.NC} Connected to Grafana {version} at {grafana_url}")
    else:
        print(f"  {Colors.RED}✗ Cannot connect to Grafana at {grafana_url}{Colors.NC}")
        return 1
    print("")

    # Run imports
    import_organizations(ctx)
    import_datasources(ctx)
    import_folders(ctx)
    import_teams(ctx)
    import_service_accounts(ctx)
    import_alerting(ctx)
    import_dashboards(ctx)
    import_sso(ctx)
    generate_tfvars(ctx)

    # Import existing resources into Terraform state
    if not ctx.skip_tf_import:
        run_terraform_imports(ctx)

    # Print summary
    print_summary(ctx)

    return 0


if __name__ == "__main__":
    sys.exit(main())
